# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWE4ZTRkYTg1MTE3OWQwMmU3ZThjZTAzZmUzMzE5ZDc3OTcyZTMxYzYyZDViYzlmZWM3OTQyZmZhMTFiNDRiNmVhODUyZTE4YjZiMzkyZGM0ZjViZjAzNGE4YWIzZDM5NDgxYjg1MDczNDdiMmE1MDNjOTBkMTA4NWQ2MmE0NTg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
